from __future__ import annotations

import json
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from videocp.errors import DownloadError
from videocp.runtime_log import full_url, log_info, log_warn

NETSCAPE_COOKIE_HEADER = "# Netscape HTTP Cookie File\n# This file is generated by videocp\n\n"
YTDLP_FORMAT_SORT = "res,fps,vcodec:h264,acodec:m4a"

_PLAYLIST_PATTERNS = (
    # YouTube
    re.compile(r"youtube\.com/@[^/]+(/(?:shorts|videos|streams))?/?$", re.IGNORECASE),
    re.compile(r"youtube\.com/channel/[^/]+", re.IGNORECASE),
    re.compile(r"youtube\.com/playlist\?", re.IGNORECASE),
    re.compile(r"youtube\.com/c/[^/]+", re.IGNORECASE),
    re.compile(r"youtube\.com/user/[^/]+", re.IGNORECASE),
    # Instagram profile / reels tab (not single post/reel)
    re.compile(r"instagram\.com/(?!p/|reel/|stories/|explore/|accounts/|direct/)[^/?#]+(/reels)?/?$", re.IGNORECASE),
)


@dataclass(slots=True)
class YtdlpMetadata:
    id: str
    title: str
    uploader: str
    site: str
    url: str


def write_netscape_cookies(cookies: list[dict[str, Any]], path: Path) -> None:
    """Write Playwright cookies to a Netscape cookie file for yt-dlp --cookies."""
    lines = [NETSCAPE_COOKIE_HEADER]
    for cookie in cookies:
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        domain = cookie.get("domain", "")
        cookie_path = cookie.get("path", "/")
        secure = "TRUE" if cookie.get("secure", False) else "FALSE"
        expires = str(max(0, int(cookie.get("expires", 0))))
        domain_flag = "TRUE" if domain.startswith(".") else "FALSE"
        lines.append(f"{domain}\t{domain_flag}\t{cookie_path}\t{secure}\t{expires}\t{name}\t{value}\n")
    path.write_text("".join(lines), encoding="utf-8")


def is_ytdlp_playlist_url(url: str) -> bool:
    """Check if a URL looks like a playlist/profile page handled by yt-dlp."""
    return any(pattern.search(url) for pattern in _PLAYLIST_PATTERNS)


@dataclass(slots=True)
class YtdlpPlaylistResult:
    video_urls: list[str]
    uploader: str


def expand_ytdlp_playlist(
    url: str,
    max_videos: int,
    cookies_file: Path | None = None,
) -> YtdlpPlaylistResult:
    """Expand a playlist/channel URL to individual video URLs via yt-dlp."""
    cmd = [
        "yt-dlp",
        "--flat-playlist",
        "--dump-json",
        "--no-warnings",
        "--playlist-items", f"1:{max_videos}",
    ]
    if cookies_file is not None:
        cmd.extend(["--cookies", str(cookies_file)])
    cmd.append(url)
    log_info("ytdlp.playlist.start", url=full_url(url), max_videos=max_videos)
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    except FileNotFoundError:
        raise DownloadError("yt-dlp not found. Install it: pip install yt-dlp or brew install yt-dlp")
    except subprocess.TimeoutExpired:
        raise DownloadError("yt-dlp playlist expansion timed out after 120 seconds")
    if result.returncode != 0:
        stderr = result.stderr.strip()
        raise DownloadError(f"yt-dlp playlist expansion failed: {stderr or 'unknown error'}")

    video_urls: list[str] = []
    uploader = ""
    for line in result.stdout.strip().splitlines():
        if not line.strip():
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        # flat-playlist entries have 'url' (full URL) or 'id' (video id)
        entry_url = entry.get("url", "")
        if not entry_url and entry.get("id"):
            entry_url = f"https://www.youtube.com/watch?v={entry['id']}"
        if entry_url:
            video_urls.append(entry_url)
        if not uploader:
            uploader = str(entry.get("uploader", entry.get("channel", "")))

    log_info("ytdlp.playlist.complete", url=full_url(url), videos=len(video_urls), uploader=uploader)
    return YtdlpPlaylistResult(video_urls=video_urls, uploader=uploader)


def fetch_ytdlp_metadata(url: str, cookies_file: Path | None = None) -> YtdlpMetadata:
    """Fetch video metadata via yt-dlp --dump-json without downloading."""
    cmd = ["yt-dlp", "--dump-json", "--no-download", "--no-warnings"]
    if cookies_file is not None:
        cmd.extend(["--cookies", str(cookies_file)])
    cmd.append(url)
    log_info("ytdlp.metadata.start", url=full_url(url))
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    except FileNotFoundError:
        raise DownloadError("yt-dlp not found. Install it: pip install yt-dlp or brew install yt-dlp")
    except subprocess.TimeoutExpired:
        raise DownloadError("yt-dlp metadata fetch timed out after 60 seconds")
    if result.returncode != 0:
        stderr = result.stderr.strip()
        raise DownloadError(f"yt-dlp metadata failed: {stderr or 'unknown error'}")
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise DownloadError(f"yt-dlp returned invalid JSON: {exc}")
    meta = YtdlpMetadata(
        id=str(data.get("id", "")),
        title=str(data.get("title", "")),
        uploader=str(data.get("uploader", data.get("channel", data.get("uploader_id", "")))),
        site=str(data.get("extractor_key", data.get("extractor", ""))).lower(),
        url=url,
    )
    log_info(
        "ytdlp.metadata.complete",
        id=meta.id,
        title=meta.title,
        uploader=meta.uploader,
        site=meta.site,
    )
    return meta


def download_with_ytdlp(
    url: str,
    output_path: Path,
    cookies_file: Path | None = None,
    timeout_secs: int = 300,
) -> None:
    """Download video using yt-dlp subprocess."""
    temp_template = str(output_path.with_suffix(".%(ext)s"))
    cmd = [
        "yt-dlp",
        "--no-warnings",
        "--no-playlist",
        "-S", YTDLP_FORMAT_SORT,
        "-o", temp_template,
        "--merge-output-format", "mp4",
    ]
    if cookies_file is not None:
        cmd.extend(["--cookies", str(cookies_file)])
    cmd.append(url)
    log_info("ytdlp.download.start", url=full_url(url), output=str(output_path))
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout_secs)
    except FileNotFoundError:
        raise DownloadError("yt-dlp not found. Install it: pip install yt-dlp or brew install yt-dlp")
    except subprocess.TimeoutExpired:
        raise DownloadError(f"yt-dlp download timed out after {timeout_secs} seconds")
    if result.returncode != 0:
        stderr = result.stderr.strip()
        raise DownloadError(f"yt-dlp download failed: {stderr or 'unknown error'}")
    # yt-dlp may produce a file with a different extension; find the actual output
    if not output_path.exists():
        # look for the file yt-dlp actually created (e.g. .webm, .mkv merged to .mp4)
        parent = output_path.parent
        stem = output_path.stem
        candidates = sorted(parent.glob(f"{stem}.*"), key=lambda p: p.stat().st_mtime, reverse=True)
        actual = next((c for c in candidates if c.suffix != ".json" and c.suffix != ".part"), None)
        if actual is not None and actual != output_path:
            actual.rename(output_path)
        elif not output_path.exists():
            raise DownloadError(f"yt-dlp completed but output file not found: {output_path}")
    log_info("ytdlp.download.complete", output=str(output_path), bytes=output_path.stat().st_size)
